version: '3'

services:
  spacemuffin:
    image: tactilenews/spacemuffin
    build: .
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/spacemuffin
      - /spacemuffin/node_modules
    command: yarn run dev
